-- Generated by scripts/generate-seed.mjs -- do not edit by hand.
-- Re-run: node scripts/generate-seed.mjs

insert into public.posts
  (slug, title, dek, excerpt, category, content, author_name, author_bio, read_minutes, tags, is_published, published_at)
values (
  'the-art-of-slow-reading',
  'The Art of Slow Reading in a Fast World',
  'Why the best ideas require patience, and how to reclaim your attention from the algorithm.',
  'Why the best ideas require patience, and how to reclaim your attention from the algorithm.',
  'Essay',
  '<p class="animate-fade-in-up">We''ve optimized for speed. Infinite scroll, TL;DR summaries, fifteen-second videos, AI-generated summaries of AI-generated summaries. The modern internet treats reading as a throughput problem — how much content can you consume per minute?</p>

        <p class="animate-fade-in-up delay-1">But understanding doesn''t scale with velocity.</p>

        <p class="animate-fade-in-up delay-2">When you read quickly, you''re not reading — you''re scanning. You''re pattern-matching against what you already know, extracting the gist, discarding the texture. The gist is useful for traffic reports and weather forecasts. It''s fatal for ideas that change how you think.</p>

        <h2>The Throughput Trap</h2>

        <p class="animate-fade-in-up delay-3">The algorithm doesn''t want you to understand. It wants you to engage. Engagement means time on platform, clicks, shares, comments — metrics that correlate loosely with comprehension and not at all with wisdom.</p>

        <p class="animate-fade-in-up delay-4">A 2019 study from the University of California found that readers who took notes by hand retained conceptual information significantly better than those who typed notes on laptops. The constraint of speed forced synthesis. You can''t write as fast as you can type, so you <em>must</em> decide what matters.</p>

        <blockquote class="animate-fade-in-up delay-5">
          "We are not only what we read — we are how we read."
        </blockquote>

        <p class="animate-fade-in-up delay-6">Maryanne Wolf, cognitive neuroscientist and author of <em>Reader, Come Home</em>, argues that the reading brain is plastic. The more we skim, the more we lose the capacity for deep reading — the slow, immersive, reflective process that builds critical thinking, empathy, and insight.</p>

        <h2>What We Lose When We Rush</h2>

        <p class="animate-fade-in-up">Deep reading isn''t just slower scanning. It''s a different cognitive mode entirely:</p>

        <ul class="animate-fade-in-up delay-1">
          <li><strong>Connection:</strong> Slow reading lets you link ideas across paragraphs, chapters, books. The synthetic insight — the "aha" that combines two distant concepts — only arrives when both concepts are fully loaded in working memory.</li>
          <li><strong>Resistance:</strong> A difficult passage forces you to pause, reread, sit with confusion. That friction is where learning happens. Skimming removes the friction and the learning.</li>
          <li><strong>Empathy:</strong> Narrative fiction read slowly activates the same neural regions as lived experience. You don''t just understand the character — you simulate their perspective. Speed-reading a novel is like speed-dating a spouse.</li>
          <li><strong>Memory:</strong> The spacing effect — distributing exposure over time — beats massed practice. Reading one book deeply over two weeks embeds it better than reading seven books in a weekend.</li>
        </ul>

        <h2>Reclaiming the Pace</h2>

        <p class="animate-fade-in-up delay-2">You don''t need a digital detox. You need a reading practice.</p>

        <h3>1. Choose Friction</h3>
        <p class="animate-fade-in-up delay-3">Buy the physical book. Use an e-ink reader without a browser. Print the essay. The device that only reads <em>only reads</em>, and that constraint is a feature.</p>

        <h3>2. Read with a Pen</h3>
        <p class="animate-fade-in-up delay-4">Marginalia forces engagement. Underline, question, argue, connect. A book without marks is a conversation you didn''t participate in.</p>

        <h3>3. One Book at a Time</h3>
        <p class="animate-fade-in-up delay-5">Parallel reading fractures attention. Finish one, then start the next. The completeness matters.</p>

        <h3>4. Schedule the Slow</h3>
        <p class="animate-fade-in-up delay-6">Protect the time. Morning coffee, evening wind-down, Sunday afternoon. Treat it like a meeting with your smarter self.</p>

        <h3>5. Write About What You Read</h3>
        <p class="animate-fade-in-up">Even a paragraph. Even a private note. Writing is thinking made visible. If you can''t explain it simply, you don''t understand it yet.</p>

        <h2>The Long View</h2>

        <p class="animate-fade-in-up">The essays that changed your life — how many did you read in a hurry? The books you return to — how many did you skim?</p>

        <p class="animate-fade-in-up delay-1">The internet will keep accelerating. The algorithm will keep optimizing for your attention, not your understanding. That''s its job.</p>

        <p class="animate-fade-in-up delay-2">Yours is to decide what''s worth your time. And then to give it the time it deserves.</p>

        <p class="animate-fade-in-up delay-3">Slowly.</p>',
  'Alex Chen',
  'Writer, reader, occasional builder of things.',
  8,
  ARRAY['Reading', 'Attention', 'Culture']::text[],
  true,
  '2026-09-15'::timestamptz
)
on conflict (slug) do update set
  title = excluded.title,
  dek = excluded.dek,
  excerpt = excluded.excerpt,
  category = excluded.category,
  content = excluded.content,
  author_name = excluded.author_name,
  author_bio = excluded.author_bio,
  read_minutes = excluded.read_minutes,
  tags = excluded.tags,
  published_at = excluded.published_at;

insert into public.posts
  (slug, title, dek, excerpt, category, content, author_name, author_bio, read_minutes, tags, is_published, published_at)
values (
  'finding-signal-in-noise',
  'Finding Signal in the Noise',
  'How to filter what matters in an age of infinite information.',
  'How to filter what matters in an age of infinite information.',
  'Essay',
  '<p class="animate-fade-in-up">The problem isn''t scarcity. It''s abundance.</p>

        <p class="animate-fade-in-up delay-1">Fifty years ago, a curious person had to hunt for information — visit libraries, write letters, wait for journals. Today, the world''s knowledge arrives in a firehose: 500 million tweets daily, 4 million blog posts, 720,000 hours of video uploaded every hour. The signal hasn''t grown. The noise has exploded.</p>

        <h2>The Attention Economy''s Tax</h2>

        <p class="animate-fade-in-up delay-2">Every platform is designed to maximize time-on-site, not truth-discovery. Algorithms optimize for engagement — outrage, novelty, confirmation — not accuracy or depth. The loudest voices aren''t the wisest; they''re the most optimized.</p>

        <p class="animate-fade-in-up delay-3">This creates a paradox: we have more access to expertise than ever, yet it''s harder to find. The expert''s careful analysis drowns in a sea of hot takes. The nuanced essay loses to the thread. The signal exists, but the noise has better distribution.</p>

        <blockquote class="animate-fade-in-up delay-4">
          "Information is not knowledge. Knowledge is not wisdom. Wisdom is not truth."
        </blockquote>

        <h2>Building Your Filter</h2>

        <p class="animate-fade-in-up delay-5">You can''t consume everything. You need a personal filter — a set of heuristics that let signal through while catching noise.</p>

        <h3>1. Trust People, Not Platforms</h3>
        <p class="animate-fade-in-up">Follow thinkers, not topics. A trusted curator''s recommendation beats any algorithm. Build a network of people whose judgment you respect — then read what they read.</p>

        <h3>2. Favor Age Over Novelty</h3>
        <p class="animate-fade-in-up delay-1">Lindy effect: the longer something has survived, the longer it will survive. A book still read after 50 years has signal. A viral thread from Tuesday likely doesn''t. Default to old books, classic papers, time-tested ideas.</p>

        <h3>3. Seek Primary Sources</h3>
        <p class="animate-fade-in-up delay-2">Secondary sources add distortion. Read the paper, not the press release. Watch the talk, not the clip. Listen to the podcast, not the highlight reel. Each layer of summarization loses nuance.</p>

        <h3>4. Limit Input Channels</h3>
        <p class="animate-fade-in-up delay-3">You don''t need Twitter, Reddit, Hacker News, LinkedIn, and five newsletters. Pick two. Go deep. The marginal value of the fifth source is negative — it adds noise without signal.</p>

        <h3>5. Create Output to Test Input</h3>
        <p class="animate-fade-in-up delay-4">Write about what you read. Teach it. Build with it. If you can''t explain an idea simply, you haven''t actually received its signal — you''ve just cached noise.</p>

        <h2>The Discipline of Ignoring</h2>

        <p class="animate-fade-in-up">The most powerful filter is the willingness to miss out. Most information is irrelevant to your life and work. Ignoring it isn''t ignorance — it''s focus.</p>

        <p class="animate-fade-in-up delay-1">The person who reads three great books a year understands more than the person who skims three hundred articles a week. Depth compounds. Breadth without depth is just trivia.</p>

        <p class="animate-fade-in-up delay-2">Signal finds you when you stop chasing noise.</p>',
  'Alex Chen',
  'Writer, reader, occasional builder of things.',
  7,
  ARRAY['Attention', 'Technology', 'Focus']::text[],
  true,
  '2026-09-10'::timestamptz
)
on conflict (slug) do update set
  title = excluded.title,
  dek = excluded.dek,
  excerpt = excluded.excerpt,
  category = excluded.category,
  content = excluded.content,
  author_name = excluded.author_name,
  author_bio = excluded.author_bio,
  read_minutes = excluded.read_minutes,
  tags = excluded.tags,
  published_at = excluded.published_at;

insert into public.posts
  (slug, title, dek, excerpt, category, content, author_name, author_bio, read_minutes, tags, is_published, published_at)
values (
  'the-geometry-of-habits',
  'The Geometry of Habits',
  'Why small changes compound, and how to design routines that actually stick.',
  'Why small changes compound, and how to design routines that actually stick.',
  'Essay',
  '<p class="animate-fade-in-up">We think habits are about willpower. They''re not. They''re about geometry.</p>

        <p class="animate-fade-in-up delay-1">A habit is a trajectory. Each repetition is a point on a curve. The curve''s shape — its slope, its inflection points, its asymptotes — determines whether the habit survives or collapses.</p>

        <h2>The Compound Curve</h2>

        <p class="animate-fade-in-up delay-2">James Clear popularized the 1% rule: get 1% better daily, and you''re 37x better in a year. The math is clean: 1.01^365 ≈ 37.8. But the geometry is messier.</p>

        <p class="animate-fade-in-up delay-3">Real progress isn''t a smooth exponential. It''s a series of plateaus punctuated by breakthroughs. The curve looks like stairs, not a ramp. Most people quit on the flat parts, not the steep ones.</p>

        <blockquote class="animate-fade-in-up delay-4">
          "We overestimate what we can do in a day, and underestimate what we can do in a decade."
        </blockquote>

        <h2>Three Geometric Principles</h2>

        <h3>1. Slope > Position</h3>
        <p class="animate-fade-in-up">Your current level matters less than your rate of change. A beginner with a steep slope overtakes an expert with a flat one. The question isn''t "How good am I?" — it''s "Am I improving?"</p>

        <p class="animate-fade-in-up delay-1">This is why starting small works. A habit with a sustainable slope beats an ambitious one that flatlines. Reading one page daily (slope: 365 pages/year) beats reading fifty pages once a month (slope: 600 pages/year, but zero for 29 days).</p>

        <h3>2. Friction Shapes the Curve</h3>
        <p class="animate-fade-in-up delay-2">Every habit has activation energy — the friction between intention and action. High friction = shallow slope. Low friction = steep slope.</p>

        <p class="animate-fade-in-up delay-3">Reduce friction geometrically:
        <ul class="animate-fade-in-up delay-4">
          <li><strong>Spatial:</strong> Put the book on your pillow. The guitar on its stand. The running shoes by the door.</li>
          <li><strong>Temporal:</strong> Anchor to existing routines. After coffee, write. After brushing, floss.</li>
          <li><strong>Cognitive:</strong> Decide once. "I write at 7am" removes the daily decision tax.</li>
        </ul>
        </p>

        <h3>3. Identity Is the Asymptote</h3>
        <p class="animate-fade-in-up delay-5">Habits approach an identity asymptote. You don''t "build a reading habit" — you become a reader. The habit is the proof; the identity is the limit.</p>

        <p class="animate-fade-in-up delay-6">This is why "I''m trying to quit smoking" fails but "I''m not a smoker" works. The former fights the old identity. The latter claims the new one. Each action votes for the identity. The curve bends toward the story you tell yourself.</p>

        <h2>Designing for Geometry</h2>

        <p class="animate-fade-in-up">Don''t set goals. Set trajectories.</p>

        <ul class="animate-fade-in-up delay-1">
          <li><strong>Minimum viable action:</strong> What''s the smallest version that still counts? Do that.</li>
          <li><strong>Never miss twice:</strong> One miss is a point. Two misses define a new slope.</li>
          <li><strong>Measure the derivative:</strong> Track rate of change, not absolute position.</li>
          <li><strong>Design the environment:</strong> Make the right action the path of least resistance.</li>
        </ul>

        <h2>The Long View</h2>

        <p class="animate-fade-in-up delay-2">A year from now, you''ll be somewhere on a curve. The curve''s shape is being decided today — by the friction you remove, the identity you claim, the small actions you repeat.</p>

        <p class="animate-fade-in-up delay-3">You don''t rise to the level of your goals. You fall to the level of your systems. And your systems are just geometry made visible.</p>',
  'Alex Chen',
  'Writer, reader, occasional builder of things.',
  6,
  ARRAY['Habits', 'Craft', 'Growth']::text[],
  true,
  '2026-09-03'::timestamptz
)
on conflict (slug) do update set
  title = excluded.title,
  dek = excluded.dek,
  excerpt = excluded.excerpt,
  category = excluded.category,
  content = excluded.content,
  author_name = excluded.author_name,
  author_bio = excluded.author_bio,
  read_minutes = excluded.read_minutes,
  tags = excluded.tags,
  published_at = excluded.published_at;

insert into public.posts
  (slug, title, dek, excerpt, category, content, author_name, author_bio, read_minutes, tags, is_published, published_at)
values (
  'why-we-write',
  'Why We Write',
  'On the impulse to make thoughts permanent, and what happens when we do.',
  'On the impulse to make thoughts permanent, and what happens when we do.',
  'Essay',
  '<p class="animate-fade-in-up">Writing is strange. You sit alone, moving fingers, arranging symbols — and somehow, across time and space, another mind receives your thought.</p>

        <p class="animate-fade-in-up delay-1">No other species does this. Bees dance. Whales sing. But only humans encode abstract reasoning into persistent marks that outlive the maker.</p>

        <h2>To Think</h2>

        <p class="animate-fade-in-up delay-2">"How do I know what I think until I see what I say?" E.M. Forster asked. The answer: you don''t.</p>

        <p class="animate-fade-in-up delay-3">Thought is slippery. It feels solid in the mind — clear, connected, complete. But try to hold it. It dissolves. Writing pins it down. The act of phrasing forces precision. You discover gaps you didn''t know existed. You find contradictions hiding in the clarity.</p>

        <blockquote class="animate-fade-in-up delay-4">
          "Writing is thinking. To write well is to think clearly. That''s why it''s so hard."
        </blockquote>

        <p class="animate-fade-in-up delay-5">The best writers aren''t the ones with the best thoughts. They''re the ones willing to endure the friction of making thoughts legible — to themselves first, then others.</p>

        <h2>To Remember</h2>

        <p class="animate-fade-in-up">Memory is reconstruction, not retrieval. Every recall rewrites. Writing is the only way to fix a thought in time — to have a conversation with your past self that doesn''t drift.</p>

        <p class="animate-fade-in-up delay-1">I read my notebooks from five years ago and meet a stranger. The writing preserves a version of me that memory has edited. Without it, that self is gone.</p>

        <h2>To Connect</h2>

        <p class="animate-fade-in-up delay-2">A published essay is a message in a bottle. You throw it into the network and wait. Sometimes, someone finds it. They write back: <em>This is exactly what I needed.</em> Or: <em>You''re wrong about this.</em> Either way, a connection forms.</p>

        <p class="animate-fade-in-up delay-3">Writing scales intimacy. One conversation reaches one person. One essay reaches thousands — each reading it alone, in their own context, at their own pace. The writer speaks once; the reader listens many times.</p>

        <h2>To Understand</h2>

        <p class="animate-fade-in-up delay-4">You don''t write because you understand. You write <em>to</em> understand.</p>

        <p class="animate-fade-in-up delay-5">The topic you avoid is the one you need to write about. The idea that feels half-formed is the one that needs the page. Writing is the tool that turns confusion into clarity — but only if you''re willing to write badly first.</p>

        <h2>The Cost</h2>

        <p class="animate-fade-in-up">Writing requires vulnerability. To publish is to say: <em>Here is my mind. Judge it.</em> Most drafts stay private because the risk feels too high.</p>

        <p class="animate-fade-in-up delay-1">But the alternative — never writing, never clarifying, never connecting — is costlier. An unexamined thought is a weight you carry invisibly. Writing sets it down.</p>

        <h2>So Write</h2>

        <p class="animate-fade-in-up delay-2">Not for audience. Not for legacy. For the thinking it forces. For the self it reveals. For the connections it enables.</p>

        <p class="animate-fade-in-up delay-3">Write badly. Write privately. Write regularly. The geometry of the habit matters more than the quality of any single piece.</p>

        <p class="animate-fade-in-up delay-4">You write to discover what you think. And in discovering, you become someone who thinks.</p>',
  'Alex Chen',
  'Writer, reader, occasional builder of things.',
  6,
  ARRAY['Writing', 'Craft', 'Creativity']::text[],
  true,
  '2026-08-28'::timestamptz
)
on conflict (slug) do update set
  title = excluded.title,
  dek = excluded.dek,
  excerpt = excluded.excerpt,
  category = excluded.category,
  content = excluded.content,
  author_name = excluded.author_name,
  author_bio = excluded.author_bio,
  read_minutes = excluded.read_minutes,
  tags = excluded.tags,
  published_at = excluded.published_at;

