#!/usr/bin/env node
/**
 * generate-seed.mjs
 * Parses the existing static article HTML files in ./articles and emits a
 * SQL seed file (supabase/seed.sql) that upserts them into public.posts.
 *
 * This keeps the database the single source of truth for post content while
 * reusing the hand-written articles that already ship with the blog.
 *
 * Usage: node scripts/generate-seed.mjs
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const articlesDir = join(root, 'articles');

const pick = (html, re) => {
  const m = html.match(re);
  return m ? m[1].trim() : null;
};

const sqlStr = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const sqlArr = (arr) =>
  `ARRAY[${arr.map((t) => `'${t.replace(/'/g, "''")}'`).join(', ')}]::text[]`;

const files = readdirSync(articlesDir)
  .filter((f) => f.endsWith('.html') && f !== 'post.html');

const rows = [];
for (const file of files) {
  const slug = file.replace(/\.html$/, '');
  const html = readFileSync(join(articlesDir, file), 'utf8');

  const title = pick(html, /<h1 class="article__title">([\s\S]*?)<\/h1>/);
  const dek = pick(html, /<p class="article__dek">([\s\S]*?)<\/p>/);
  const category = pick(html, /<span class="article__category">([\s\S]*?)<\/span>/) || 'Essay';
  const datetime = pick(html, /<time datetime="([^"]+)"/);
  const readRaw = pick(html, /<span>(\d+)\s*min read<\/span>/);
  const readMinutes = readRaw ? parseInt(readRaw, 10) : 5;
  const authorName = pick(html, /<p class="article__author-name">([\s\S]*?)<\/p>/) || 'Alex Chen';
  const authorBio = pick(html, /<p class="article__author-bio">([\s\S]*?)<\/p>/) || '';
  const description = pick(html, /<meta name="description" content="([^"]*)"/);

  // Inner HTML of the article content block.
  const content = pick(html, /<div class="article__content">([\s\S]*?)<\/div>\s*<footer class="article__footer">/);

  // Tags from the footer.
  const tags = [...html.matchAll(/<a href="[^"]*" class="article__tag">([\s\S]*?)<\/a>/g)].map((m) =>
    m[1].trim()
  );

  // A short excerpt: strip tags from the first content paragraph.
  const firstP = pick(content || '', /<p[^>]*>([\s\S]*?)<\/p>/);
  const excerpt = (description && description.includes('—'))
    ? description.split('—').slice(1).join('—').trim()
    : (firstP ? firstP.replace(/<[^>]+>/g, '').trim().slice(0, 200) : dek);

  rows.push({
    slug,
    title,
    dek,
    excerpt,
    category,
    content: (content || '').trim(),
    authorName,
    authorBio,
    readMinutes,
    tags,
    publishedAt: datetime,
  });
}

// Sort newest first for deterministic output.
rows.sort((a, b) => (a.publishedAt < b.publishedAt ? 1 : -1));

let sql = `-- Generated by scripts/generate-seed.mjs -- do not edit by hand.\n`;
sql += `-- Re-run: node scripts/generate-seed.mjs\n\n`;
for (const r of rows) {
  sql += `insert into public.posts
  (slug, title, dek, excerpt, category, content, author_name, author_bio, read_minutes, tags, is_published, published_at)
values (
  ${sqlStr(r.slug)},
  ${sqlStr(r.title)},
  ${sqlStr(r.dek)},
  ${sqlStr(r.excerpt)},
  ${sqlStr(r.category)},
  ${sqlStr(r.content)},
  ${sqlStr(r.authorName)},
  ${sqlStr(r.authorBio)},
  ${r.readMinutes},
  ${sqlArr(r.tags)},
  true,
  ${sqlStr(r.publishedAt)}::timestamptz
)
on conflict (slug) do update set
  title = excluded.title,
  dek = excluded.dek,
  excerpt = excluded.excerpt,
  category = excluded.category,
  content = excluded.content,
  author_name = excluded.author_name,
  author_bio = excluded.author_bio,
  read_minutes = excluded.read_minutes,
  tags = excluded.tags,
  published_at = excluded.published_at;\n\n`;
}

mkdirSync(join(root, 'supabase'), { recursive: true });
writeFileSync(join(root, 'supabase', 'seed.sql'), sql);
console.log(`Wrote supabase/seed.sql with ${rows.length} posts: ${rows.map((r) => r.slug).join(', ')}`);
